server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/login?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false

    username: root
    password: 123456
#  mvc:
#    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,file:/opt/static/,classpath:/static/ #访问静态页面
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .htm
